### PR TITLE
Change font

### PR DESCRIPTION
**Pull request by corydalis10**
I changed this website font to Poppins to increase readability!
If PR has a problem, don't hesitate to tell me :)

### CODE REVIEW

**Comment by gwolf2u** [comment]
this is incomplete
only changed index page and some other elements

**Comment by corydalis10** [comment]
The new font has been changed to reflect the entire page!
Please review my PR again.

**Comment by gwolf2u** [comment]
Not sure I really want to get text bit more bigger and bolder

current
proposed

**Comment by gwolf2u** [comment]
for now let's keep what we have
appreciate the input

**Comment by corydalis10** [comment]
I respect your opinion.
I will contribute again if I have the chance.

**Pull request closed without merging**
